### PR TITLE
add support for configured host and port in generated lb-services, wi…

### PR DESCRIPTION
**Pull request by jesucarr**
…thout the need of explicit --url parameter

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
Hi @jesucarr, thank you for the pull request.

I am little bit worried about the consequences of your proposal. For people hosting their Angular client on the same server as the API backend, this change means that they have to re-generate their client services for each different hostname (dev, qa, production) they serve the app.

I am proposing to add a new cli switch to enable your feature, e.g. `--full-url`.

Thoughts?

**Comment by jesucarr** [comment]
I see what you mean... but since it's using app.get(...), it will pick up the config set for the environment and not sure if it makes more sense to integrate the lb-ng generation for the different environments (using NODE_ENV=dev, qa, production, etc), rather than assume that front and back end use the same server.

But yeah maybe a new switch to enable this is a good idea. Maybe `--conf-url` is a more descriptive name though...

**Comment by bajtos** [comment]
Hello, as part of cleaning up our backlog, I am closing pull requests that have been inactive for extended period of time.

@jesucarr If you are still keen to get this landed, then please add the new CLI switch and reopen the pull request.

**Pull request closed without merging**
